all:
  children:
    prod:
      hosts:
        worker01:
          ansible_host: 172.31.90.87
          ansible_ssh_common_args: -o StrictHostKeyChecking=no
  
        worker02:
          ansible_host: 172.31.86.63
          ansible_ssh_common_args: -o StrictHostKeyChecking=no
