all:
  children:
   ansible:
      hosts:
        localhost:
          ansible_connection: local
    prod:
      hosts:
        worker01:
          ansible_host: 172.31.90.87
        worker02:
          ansible_host: 172.31.86.63
